import { ExerciseCatalogItem } from './movementModel';

export const COMPREHENSIVE_EXERCISE_CATALOG: ExerciseCatalogItem[] = [
  // ==========================================
  // UPPER BODY: HORIZONTAL PUSH
  // ==========================================
  {
    name: 'Push-Ups (Standard / Deficit)',
    targetMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders', 'core'],
    equipment: 'bodyweight',
    movementPattern: 'horizontal_push',
    movementSubtype: 'bodyweight_pushup',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'none',
    stabilityDemand: 'moderate',
    fatigueCost: 2,
    recoveryDemandHours: 24,
    difficulty: 'beginner',
    defaultRepRange: { min: 8, max: 15 },
    defaultRestSeconds: 60,
    isTimeBased: false,
    progressionMethod: 'bodyweight_ladder',
    regressions: ['Incline Push-Ups', 'Knee Push-Ups'],
    progressions: ['Deficit Push-Ups', 'Diamond Push-Ups', 'Archer Push-Ups'],
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: true,
    instructions: 'Keep a rigid plank posture with core and glutes engaged. Lower chest smoothly to floor depth, press up explosively through palms.',
    formTips: [
      'Maintain neutral neck and braced abdominal wall throughout.',
      'Elbows should track back at roughly 45 degrees, not flared out at 90.',
      'Lock out with controlled shoulder protraction at the top.'
    ],
    videoUrl: 'https://www.youtube.com/embed/IODxDxX7oi4'
  },
  {
    name: 'Deficit Push-Ups',
    targetMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders', 'core'],
    equipment: 'other',
    movementPattern: 'horizontal_push',
    movementSubtype: 'deficit_pushup',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'none',
    stabilityDemand: 'moderate',
    fatigueCost: 3,
    recoveryDemandHours: 36,
    difficulty: 'intermediate',
    defaultRepRange: { min: 8, max: 12 },
    defaultRestSeconds: 75,
    isTimeBased: false,
    progressionMethod: 'bodyweight_ladder',
    regressions: ['Push-Ups (Standard / Deficit)'],
    progressions: ['Weighted Push-Ups', 'Ring Push-Ups'],
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: true,
    instructions: 'Grip push-up handles or blocks. Lower chest down past hand level for a deep pectoral stretch, then press to full lockout.',
    formTips: [
      'Emphasize the deep bottom stretch without letting shoulders roll forward.',
      'Keep core rigid to avoid lumbar hyperextension.',
      'Control the lowering phase for 2-3 seconds.'
    ],
    videoUrl: 'https://www.youtube.com/embed/IODxDxX7oi4'
  },
  {
    name: 'Dumbbell Floor Press',
    targetMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'dumbbell',
    movementPattern: 'horizontal_push',
    movementSubtype: 'floor_press',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'none',
    stabilityDemand: 'moderate',
    fatigueCost: 3,
    recoveryDemandHours: 36,
    difficulty: 'beginner',
    defaultRepRange: { min: 8, max: 12 },
    defaultRestSeconds: 75,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    regressions: ['Push-Ups (Standard / Deficit)'],
    progressions: ['Barbell Flat Bench Press', 'Incline Dumbbell Press'],
    benchRequired: false, // EXPLICITLY NO BENCH NEEDED
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Lie flat on the floor with knees bent and feet planted. Press dumbbells vertically over chest; lower until upper arms gently brush floor.',
    formTips: [
      'Gently touch upper arms to the floor; pause briefly before pressing up to eliminate bounce.',
      'Tuck elbows at 45 degrees to protect anterior shoulder capsule.',
      'Drive dumbbells straight up toward the ceiling with active pec contraction.'
    ],
    videoUrl: 'https://www.youtube.com/embed/uUGDRwge4F8'
  },
  {
    name: 'Barbell Flat Bench Press',
    targetMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'barbell',
    movementPattern: 'horizontal_push',
    movementSubtype: 'bench_press',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'light',
    stabilityDemand: 'high',
    fatigueCost: 4,
    recoveryDemandHours: 48,
    difficulty: 'intermediate',
    defaultRepRange: { min: 6, max: 10 },
    defaultRestSeconds: 90,
    isTimeBased: false,
    progressionMethod: 'linear_load',
    regressions: ['Dumbbell Floor Press', 'Push-Ups (Standard / Deficit)'],
    benchRequired: true,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Lie on flat bench. Grip bar slightly wider than shoulder width. Lower bar smoothly to mid-chest, drive up explosively.',
    formTips: ['Retract shoulder blades into bench.', 'Maintain leg drive with heels planted.', 'Keep wrists stacked.'],
    videoUrl: 'https://www.youtube.com/embed/rT7DgCr-3pg'
  },
  {
    name: 'Incline Dumbbell Press',
    targetMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'dumbbell',
    movementPattern: 'horizontal_push',
    movementSubtype: 'incline_press',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'light',
    stabilityDemand: 'high',
    fatigueCost: 3,
    recoveryDemandHours: 48,
    difficulty: 'intermediate',
    defaultRepRange: { min: 8, max: 12 },
    defaultRestSeconds: 75,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    benchRequired: true,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Set bench to 30-45 degrees. Press dumbbells upwards in smooth arc emphasizing clavicular head of pectorals.',
    formTips: ['Do not set incline too steep (keep around 30 degrees).', 'Control the eccentric stretch.'],
    videoUrl: 'https://www.youtube.com/embed/8iPEnn-ltC8'
  },

  // ==========================================
  // UPPER BODY: HORIZONTAL PULL
  // ==========================================
  {
    name: 'Split-Stance One-Arm Dumbbell Row',
    targetMuscle: 'back',
    secondaryMuscles: ['biceps', 'rear_delt' as any, 'core'],
    equipment: 'dumbbell',
    movementPattern: 'horizontal_pull',
    movementSubtype: 'split_stance_row',
    mechanic: 'compound',
    laterality: 'unilateral',
    axialLoading: 'light',
    stabilityDemand: 'moderate',
    fatigueCost: 3,
    recoveryDemandHours: 36,
    difficulty: 'beginner',
    defaultRepRange: { min: 8, max: 12 },
    defaultRestSeconds: 60,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    regressions: ['Inverted Bodyweight Row'],
    progressions: ['Dumbbell Bent-Over Row', 'Barbell Bent-Over Row'],
    benchRequired: false, // EXPLICITLY NO BENCH NEEDED
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Take a staggered split stance. Hinge forward at the hips with a flat back, resting your non-working forearm or hand on your front thigh or sturdy surface. Pull the dumbbell smoothly toward your hip pocket.',
    formTips: [
      'Lead with your elbow, driving it towards the ceiling and back pocket.',
      'Keep shoulders square to the floor without torso rotation.',
      'Squeeze the latissimus dorsi at peak contraction for 1 second.'
    ],
    videoUrl: 'https://www.youtube.com/embed/pYcpY20QaE8'
  },
  {
    name: 'One-Arm Dumbbell Row (Bench-Supported)',
    targetMuscle: 'back',
    secondaryMuscles: ['biceps', 'rear_delt' as any],
    equipment: 'dumbbell',
    movementPattern: 'horizontal_pull',
    movementSubtype: 'bench_supported_row',
    mechanic: 'compound',
    laterality: 'unilateral',
    axialLoading: 'none',
    stabilityDemand: 'low',
    fatigueCost: 2,
    recoveryDemandHours: 36,
    difficulty: 'beginner',
    defaultRepRange: { min: 8, max: 12 },
    defaultRestSeconds: 60,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    benchRequired: true,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Place same-side knee and hand on flat bench. Pull dumbbell vertically towards hip crease.',
    formTips: ['Keep back parallel to bench.', 'Drive elbow up and back.'],
    videoUrl: 'https://www.youtube.com/embed/pYcpY20QaE8'
  },
  {
    name: 'Dumbbell Bent-Over Row',
    targetMuscle: 'back',
    secondaryMuscles: ['biceps', 'rear_delt' as any, 'core'],
    equipment: 'dumbbell',
    movementPattern: 'horizontal_pull',
    movementSubtype: 'bilateral_bent_row',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'moderate',
    stabilityDemand: 'moderate',
    fatigueCost: 3,
    recoveryDemandHours: 48,
    difficulty: 'intermediate',
    defaultRepRange: { min: 8, max: 12 },
    defaultRestSeconds: 75,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Stand with feet shoulder-width, hinge hips back at 45 degrees with neutral spine. Pull both dumbbells towards hip crease.',
    formTips: ['Keep chest proud and avoid lumbar rounding.', 'Drive elbows back, squeezing shoulder blades together.'],
    videoUrl: 'https://www.youtube.com/embed/pYcpY20QaE8'
  },
  {
    name: 'Inverted Bodyweight Row',
    targetMuscle: 'back',
    secondaryMuscles: ['biceps', 'core'],
    equipment: 'bodyweight',
    movementPattern: 'horizontal_pull',
    movementSubtype: 'inverted_row',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'none',
    stabilityDemand: 'moderate',
    fatigueCost: 2,
    recoveryDemandHours: 24,
    difficulty: 'beginner',
    defaultRepRange: { min: 8, max: 12 },
    defaultRestSeconds: 60,
    isTimeBased: false,
    progressionMethod: 'bodyweight_ladder',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Grip a low bar or table edge with straight body. Pull chest up to bar while maintaining rigid abdominal plank.',
    formTips: ['Keep glutes clenched and body in a straight line.', 'Touch chest to bar with full scapular retraction.'],
    videoUrl: 'https://www.youtube.com/embed/pYcpY20QaE8'
  },

  // ==========================================
  // UPPER BODY: VERTICAL PULL
  // ==========================================
  {
    name: 'Pull-Ups / Chin-Ups',
    targetMuscle: 'back',
    secondaryMuscles: ['biceps', 'core'],
    equipment: 'bodyweight',
    movementPattern: 'vertical_pull',
    movementSubtype: 'bodyweight_pullup',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'none',
    stabilityDemand: 'high',
    fatigueCost: 4,
    recoveryDemandHours: 48,
    difficulty: 'intermediate',
    defaultRepRange: { min: 4, max: 8 },
    defaultRestSeconds: 90,
    isTimeBased: false,
    progressionMethod: 'bodyweight_ladder',
    regressions: ['Negative Pull-Ups (Eccentric)', 'Inverted Bodyweight Row'],
    progressions: ['Weighted Pull-Ups'],
    benchRequired: false,
    pullupBarRequired: true,
    pushupHandlesCompatible: false,
    instructions: 'Hang from overhead bar. Pull chest up until chin clears bar. Lower under strict eccentric control without swinging.',
    formTips: [
      'Begin the movement by depressing shoulder blades down away from ears.',
      'Drive elbows down into your ribs.',
      'Control the negative descent over 2-3 seconds.'
    ],
    videoUrl: 'https://www.youtube.com/embed/eGo4IYlbE5g'
  },
  {
    name: 'Negative Pull-Ups (Eccentric)',
    targetMuscle: 'back',
    secondaryMuscles: ['biceps', 'core'],
    equipment: 'bodyweight',
    movementPattern: 'vertical_pull',
    movementSubtype: 'eccentric_pullup',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'none',
    stabilityDemand: 'moderate',
    fatigueCost: 3,
    recoveryDemandHours: 48,
    difficulty: 'beginner',
    defaultRepRange: { min: 3, max: 6 },
    defaultRestSeconds: 75,
    isTimeBased: false,
    progressionMethod: 'bodyweight_ladder',
    regressions: ['Inverted Bodyweight Row'],
    progressions: ['Pull-Ups / Chin-Ups'],
    benchRequired: false,
    pullupBarRequired: true,
    pushupHandlesCompatible: false,
    instructions: 'Step or jump up to top chin-over-bar position. Resist gravity and lower yourself down as slowly as possible (target 4-5 seconds). Step up and repeat.',
    formTips: [
      'Focus strictly on maximum eccentric braking control.',
      'Keep core engaged to prevent swaying.',
      'Perform fewer, higher-quality slow reps (3-5 reps).'
    ],
    videoUrl: 'https://www.youtube.com/embed/eGo4IYlbE5g'
  },
  {
    name: 'Dumbbell Pullover',
    targetMuscle: 'back',
    secondaryMuscles: ['chest', 'triceps'],
    equipment: 'dumbbell',
    movementPattern: 'vertical_pull',
    movementSubtype: 'lat_pullover',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'none',
    stabilityDemand: 'moderate',
    fatigueCost: 2,
    recoveryDemandHours: 36,
    difficulty: 'beginner',
    defaultRepRange: { min: 10, max: 15 },
    defaultRestSeconds: 60,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    benchRequired: false, // Can be performed on floor or foam roller
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Lie flat on floor with knees bent holding single dumbbell overhead. Lower dumbbell in controlled arc behind head until lat stretch, pull back to chest.',
    formTips: ['Keep slight bend in elbows.', 'Feel deep stretch through lats and ribcage.'],
    videoUrl: 'https://www.youtube.com/embed/pYcpY20QaE8'
  },

  // ==========================================
  // UPPER BODY: VERTICAL PUSH
  // ==========================================
  {
    name: 'Standing Dumbbell Shoulder Press',
    targetMuscle: 'shoulders',
    secondaryMuscles: ['triceps', 'core'],
    equipment: 'dumbbell',
    movementPattern: 'vertical_push',
    movementSubtype: 'overhead_press',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'moderate',
    stabilityDemand: 'high',
    fatigueCost: 3,
    recoveryDemandHours: 48,
    difficulty: 'beginner',
    defaultRepRange: { min: 8, max: 12 },
    defaultRestSeconds: 75,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Stand tall with core and glutes braced. Press dumbbells vertically overhead to full lockout without overarching lumbar spine.',
    formTips: [
      'Brace abs tight to maintain neutral pelvis; do not lean backward.',
      'Press in slight natural arc, locking out directly over mid-foot.',
      'Control the descent back to ear/collarbone level.'
    ],
    videoUrl: 'https://www.youtube.com/embed/qEwKCR5JCog'
  },
  {
    name: 'Seated Dumbbell Shoulder Press',
    targetMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'dumbbell',
    movementPattern: 'vertical_push',
    movementSubtype: 'overhead_press',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'moderate',
    stabilityDemand: 'low',
    fatigueCost: 3,
    recoveryDemandHours: 48,
    difficulty: 'intermediate',
    defaultRepRange: { min: 8, max: 12 },
    defaultRestSeconds: 75,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    benchRequired: true,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Sit on vertical bench with back supported. Press dumbbells overhead in controlled motion.',
    formTips: ['Press vertically, avoiding excessive wrist extension.'],
    videoUrl: 'https://www.youtube.com/embed/qEwKCR5JCog'
  },
  {
    name: 'Pike Push-Ups',
    targetMuscle: 'shoulders',
    secondaryMuscles: ['triceps', 'core'],
    equipment: 'bodyweight',
    movementPattern: 'vertical_push',
    movementSubtype: 'bodyweight_overhead',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'none',
    stabilityDemand: 'moderate',
    fatigueCost: 3,
    recoveryDemandHours: 36,
    difficulty: 'intermediate',
    defaultRepRange: { min: 6, max: 10 },
    defaultRestSeconds: 75,
    isTimeBased: false,
    progressionMethod: 'bodyweight_ladder',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: true,
    instructions: 'Pike hips high into an inverted V. Lower crown of head forward toward floor between hands, press floor away back to lockout.',
    formTips: ['Lower head forward forming a tripod with hands.', 'Keep hips stacked high.'],
    videoUrl: 'https://www.youtube.com/embed/qEwKCR5JCog'
  },

  // ==========================================
  // UPPER BODY: SHOULDER ABDUCTION & REAR DELT
  // ==========================================
  {
    name: 'Dumbbell Lateral Raise',
    targetMuscle: 'shoulders',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    movementPattern: 'shoulder_abduction',
    movementSubtype: 'lateral_deltoid_isolation',
    mechanic: 'isolation',
    laterality: 'bilateral',
    axialLoading: 'none',
    stabilityDemand: 'low',
    fatigueCost: 1,
    recoveryDemandHours: 24,
    difficulty: 'beginner',
    defaultRepRange: { min: 12, max: 16 },
    defaultRestSeconds: 45,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Slight forward torso lean. Raise dumbbells out to sides leading with elbows until parallel with floor, then lower under control.',
    formTips: [
      'Lead with elbows, keeping hands slightly lower than elbows.',
      'Do not shrug or swing body momentum; keep neck relaxed.',
      'Control the lowering phase completely.'
    ],
    videoUrl: 'https://www.youtube.com/embed/3VcKaXpzqRo'
  },
  {
    name: 'Bent-Over Rear Delt Flyes',
    targetMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: 'dumbbell',
    movementPattern: 'rear_delt',
    movementSubtype: 'posterior_deltoid_isolation',
    mechanic: 'isolation',
    laterality: 'bilateral',
    axialLoading: 'light',
    stabilityDemand: 'low',
    fatigueCost: 1,
    recoveryDemandHours: 24,
    difficulty: 'beginner',
    defaultRepRange: { min: 12, max: 15 },
    defaultRestSeconds: 45,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Hinge forward with flat back almost parallel to floor. Raise dumbbells outward like wings with soft elbows, contracting posterior delts.',
    formTips: [
      'Focus purely on rear shoulder contraction, not scapular pinching.',
      'Use light loads with strict form.'
    ],
    videoUrl: 'https://www.youtube.com/embed/0G2_XV7slIg'
  },

  // ==========================================
  // UPPER BODY: ELBOW FLEXION (BICEPS)
  // ==========================================
  {
    name: 'Standing Dumbbell Bicep Curl',
    targetMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    movementPattern: 'elbow_flexion',
    movementSubtype: 'supinated_bicep_curl',
    mechanic: 'isolation',
    laterality: 'bilateral',
    axialLoading: 'none',
    stabilityDemand: 'low',
    fatigueCost: 1,
    recoveryDemandHours: 24,
    difficulty: 'beginner',
    defaultRepRange: { min: 10, max: 14 },
    defaultRestSeconds: 60,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Stand feet shoulder-width. Curl dumbbells while supinating wrists outward for peak bicep contraction; lower under full control.',
    formTips: [
      'Keep elbows pinned slightly in front of ribs without swinging.',
      'Turn pinky finger outward at top for maximum contraction.',
      'Lower fully into bottom stretch.'
    ],
    videoUrl: 'https://www.youtube.com/embed/sAq_ocpRh_I'
  },
  {
    name: 'Dumbbell Hammer Curl',
    targetMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    movementPattern: 'elbow_flexion',
    movementSubtype: 'neutral_hammer_curl',
    mechanic: 'isolation',
    laterality: 'bilateral',
    axialLoading: 'none',
    stabilityDemand: 'low',
    fatigueCost: 1,
    recoveryDemandHours: 24,
    difficulty: 'beginner',
    defaultRepRange: { min: 10, max: 14 },
    defaultRestSeconds: 60,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Maintain neutral thumbs-up grip throughout. Curl dumbbells towards shoulders targeting brachialis and forearm thickness.',
    formTips: ['Keep wrists locked straight.', 'No swinging at the hips.'],
    videoUrl: 'https://www.youtube.com/embed/zC3nLlEvin4'
  },

  // ==========================================
  // UPPER BODY: ELBOW EXTENSION (TRICEPS)
  // ==========================================
  {
    name: 'Overhead Dumbbell Tricep Extension',
    targetMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    movementPattern: 'elbow_extension',
    movementSubtype: 'overhead_tricep_extension',
    mechanic: 'isolation',
    laterality: 'bilateral',
    axialLoading: 'none',
    stabilityDemand: 'low',
    fatigueCost: 1,
    recoveryDemandHours: 24,
    difficulty: 'beginner',
    defaultRepRange: { min: 10, max: 14 },
    defaultRestSeconds: 60,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    benchRequired: false, // Can be done standing or seated on floor/chair
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Hold single dumbbell with both hands overhead. Lower dumbbell behind head to stretch long head of triceps, extend back up.',
    formTips: [
      'Keep elbows pointed forward, not flared out excessively.',
      'Maintain ribcage pulled down with tight abs.'
    ],
    videoUrl: 'https://www.youtube.com/embed/YbX7Wd8jQ-Q'
  },
  {
    name: 'Dumbbell Tricep Kickbacks',
    targetMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    movementPattern: 'elbow_extension',
    movementSubtype: 'tricep_kickback',
    mechanic: 'isolation',
    laterality: 'unilateral',
    axialLoading: 'none',
    stabilityDemand: 'low',
    fatigueCost: 1,
    recoveryDemandHours: 24,
    difficulty: 'beginner',
    defaultRepRange: { min: 12, max: 15 },
    defaultRestSeconds: 45,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Hinge forward with upper arm pinned parallel to torso. Extend forearm back to full lockout, squeeze triceps for 1 second.',
    formTips: ['Do not drop the elbow between reps.'],
    videoUrl: 'https://www.youtube.com/embed/YbX7Wd8jQ-Q'
  },
  {
    name: 'Diamond Push-Ups',
    targetMuscle: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: 'bodyweight',
    movementPattern: 'horizontal_push',
    movementSubtype: 'close_grip_pushup',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'none',
    stabilityDemand: 'moderate',
    fatigueCost: 2,
    recoveryDemandHours: 36,
    difficulty: 'intermediate',
    defaultRepRange: { min: 8, max: 12 },
    defaultRestSeconds: 60,
    isTimeBased: false,
    progressionMethod: 'bodyweight_ladder',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Hands under sternum with index fingers and thumbs forming a diamond. Lower chest to hands with elbows tucked tight, press up.',
    formTips: ['Keep elbows tucked alongside ribs.'],
    videoUrl: 'https://www.youtube.com/embed/IODxDxX7oi4'
  },

  // ==========================================
  // LOWER BODY: SQUAT (BILATERAL KNEE-DOMINANT)
  // ==========================================
  {
    name: 'Dumbbell Goblet Squat',
    targetMuscle: 'legs',
    secondaryMuscles: ['core'],
    equipment: 'dumbbell',
    movementPattern: 'squat',
    movementSubtype: 'bilateral_squat',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'light',
    stabilityDemand: 'moderate',
    fatigueCost: 3,
    recoveryDemandHours: 48,
    difficulty: 'beginner',
    defaultRepRange: { min: 8, max: 12 },
    defaultRestSeconds: 75,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    regressions: ['Bodyweight Air Squat'],
    progressions: ['Barbell Back Squat', 'Bulgarian Split Squat'],
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Hold a single dumbbell vertically against your sternum with both hands cupping the top head. Squat deeply between knees with tall upright posture; drive up through mid-foot.',
    formTips: [
      'Keep elbows inside knees at the bottom of the squat to reinforce good hip abduction.',
      'Maintain full foot contact (heel, big toe, pinky toe) throughout.',
      'Brace core 360 degrees before initiating descent.'
    ],
    videoUrl: 'https://www.youtube.com/embed/MeIiIdhvXT4'
  },
  {
    name: 'Bodyweight Air Squat',
    targetMuscle: 'legs',
    secondaryMuscles: ['core'],
    equipment: 'bodyweight',
    movementPattern: 'squat',
    movementSubtype: 'bilateral_squat',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'none',
    stabilityDemand: 'low',
    fatigueCost: 1,
    recoveryDemandHours: 24,
    difficulty: 'beginner',
    defaultRepRange: { min: 12, max: 20 },
    defaultRestSeconds: 60,
    isTimeBased: false,
    progressionMethod: 'bodyweight_ladder',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Feet shoulder-width apart. Squat down until hip crease is below knee level while keeping chest proud; stand up to full extension.',
    formTips: ['Keep chest up and knees tracking over toes.'],
    videoUrl: 'https://www.youtube.com/embed/MeIiIdhvXT4'
  },
  {
    name: 'Barbell Back Squat',
    targetMuscle: 'legs',
    secondaryMuscles: ['core', 'back'],
    equipment: 'barbell',
    movementPattern: 'squat',
    movementSubtype: 'bilateral_squat',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'heavy',
    stabilityDemand: 'high',
    fatigueCost: 5,
    recoveryDemandHours: 72,
    difficulty: 'advanced',
    defaultRepRange: { min: 6, max: 10 },
    defaultRestSeconds: 120,
    isTimeBased: false,
    progressionMethod: 'linear_load',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Bar across upper traps. Descend until thighs parallel or below, drive up through midfoot.',
    formTips: ['Brace core with Valsalva maneuver.', 'Maintain knee-toe alignment.'],
    videoUrl: 'https://www.youtube.com/embed/MeIiIdhvXT4'
  },

  // ==========================================
  // LOWER BODY: HINGE (HIP-DOMINANT POSTERIOR CHAIN)
  // ==========================================
  {
    name: 'Dumbbell Romanian Deadlift (RDL)',
    targetMuscle: 'legs',
    secondaryMuscles: ['back', 'core'],
    equipment: 'dumbbell',
    movementPattern: 'hinge',
    movementSubtype: 'hip_hinge_rdl',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'moderate',
    stabilityDemand: 'moderate',
    fatigueCost: 3,
    recoveryDemandHours: 48,
    difficulty: 'beginner',
    defaultRepRange: { min: 8, max: 12 },
    defaultRestSeconds: 75,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    regressions: ['Bodyweight Glute Bridge'],
    progressions: ['Barbell Romanian Deadlift', 'Conventional Barbell Deadlift'],
    benchRequired: false, // NO BENCH NEEDED
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Hold dumbbells against front of thighs with soft knee bend. Push hips straight back as if touching a wall behind you, sliding dumbbells along shins until deep hamstring stretch; drive hips forward to lockout.',
    formTips: [
      'Movement comes entirely from the hips hinged backward, not knees bending downward.',
      'Maintain perfectly flat neutral spine; do not round shoulders.',
      'Squeeze glutes hard at the top lockout.'
    ],
    videoUrl: 'https://www.youtube.com/embed/JCXUYuzwNrM'
  },
  {
    name: 'Conventional Barbell Deadlift',
    targetMuscle: 'back',
    secondaryMuscles: ['legs', 'core'],
    equipment: 'barbell',
    movementPattern: 'hinge',
    movementSubtype: 'conventional_deadlift',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'heavy',
    stabilityDemand: 'high',
    fatigueCost: 5,
    recoveryDemandHours: 72,
    difficulty: 'advanced',
    defaultRepRange: { min: 5, max: 8 },
    defaultRestSeconds: 120,
    isTimeBased: false,
    progressionMethod: 'linear_load',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Stand midfoot under bar. Hinge, grip bar, pull slack out, drive floor away to full hip extension.',
    formTips: ['Keep bar dragged along shins.', 'Lock out hips and knees simultaneously.'],
    videoUrl: 'https://www.youtube.com/embed/JCXUYuzwNrM'
  },

  // ==========================================
  // LOWER BODY: LUNGE / UNILATERAL LEG
  // ==========================================
  {
    name: 'Bulgarian Split Squat',
    targetMuscle: 'legs',
    secondaryMuscles: ['core'],
    equipment: 'dumbbell',
    movementPattern: 'lunge_single_leg',
    movementSubtype: 'unilateral_split_squat',
    mechanic: 'compound',
    laterality: 'unilateral',
    axialLoading: 'light',
    stabilityDemand: 'high',
    fatigueCost: 4, // Very high unilateral fatigue
    recoveryDemandHours: 48,
    difficulty: 'intermediate',
    defaultRepRange: { min: 8, max: 12 },
    defaultRestSeconds: 75,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    benchRequired: false, // Can use sturdy chair, couch, step, or bench
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Elevate rear foot on a bench, chair, or step. Lower front hip until back knee hovers just above floor, drive through lead heel.',
    formTips: [
      'Maintain slight forward torso lean to load lead glute and quad evenly.',
      'Keep lead knee tracking over second toe.',
      'Control the descent without banging the rear knee.'
    ],
    videoUrl: 'https://www.youtube.com/embed/2C-uNgKwPLE'
  },
  {
    name: 'Walking Dumbbell Lunges',
    targetMuscle: 'legs',
    secondaryMuscles: ['core'],
    equipment: 'dumbbell',
    movementPattern: 'lunge_single_leg',
    movementSubtype: 'unilateral_dynamic_lunge',
    mechanic: 'compound',
    laterality: 'unilateral',
    axialLoading: 'light',
    stabilityDemand: 'moderate',
    fatigueCost: 3,
    recoveryDemandHours: 48,
    difficulty: 'intermediate',
    defaultRepRange: { min: 10, max: 14 },
    defaultRestSeconds: 60,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Step forward deliberately, lowering rear knee to gentle floor brush before stepping smoothly through into next stride.',
    formTips: ['Keep torso tall and proud.', 'Do not crash rear knee.'],
    videoUrl: 'https://www.youtube.com/embed/D7KaRcUTQeE'
  },
  {
    name: 'Dumbbell Reverse Lunges',
    targetMuscle: 'legs',
    secondaryMuscles: ['core'],
    equipment: 'dumbbell',
    movementPattern: 'lunge_single_leg',
    movementSubtype: 'unilateral_reverse_lunge',
    mechanic: 'compound',
    laterality: 'unilateral',
    axialLoading: 'light',
    stabilityDemand: 'moderate',
    fatigueCost: 3,
    recoveryDemandHours: 36,
    difficulty: 'beginner',
    defaultRepRange: { min: 8, max: 12 },
    defaultRestSeconds: 60,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Step backward into a lunge with front shin vertical. Push through front heel to return to standing.',
    formTips: ['Easier on knees than forward lunges.', 'Keep front foot fully grounded.'],
    videoUrl: 'https://www.youtube.com/embed/D7KaRcUTQeE'
  },

  // ==========================================
  // LOWER BODY: CALVES
  // ==========================================
  {
    name: 'Dumbbell Standing Calf Raise',
    targetMuscle: 'legs',
    secondaryMuscles: ['calves' as any],
    equipment: 'dumbbell',
    movementPattern: 'calf',
    movementSubtype: 'calf_plantarflexion',
    mechanic: 'isolation',
    laterality: 'bilateral',
    axialLoading: 'light',
    stabilityDemand: 'low',
    fatigueCost: 1,
    recoveryDemandHours: 24,
    difficulty: 'beginner',
    defaultRepRange: { min: 12, max: 20 },
    defaultRestSeconds: 45,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Hold dumbbells at sides with balls of feet on step edge or floor. Lower heels deep into calf stretch, explode onto big toes and pause.',
    formTips: ['Pause for 2 seconds at peak contraction.', 'Do not bounce.'],
    videoUrl: 'https://www.youtube.com/embed/gwLzBJYoWlI'
  },

  // ==========================================
  // CORE: STABILIZATION & ROTATION
  // ==========================================
  {
    name: 'Standard Forearm Plank',
    targetMuscle: 'core',
    secondaryMuscles: ['shoulders'],
    equipment: 'bodyweight',
    movementPattern: 'anti_extension',
    movementSubtype: 'isometric_anti_extension',
    mechanic: 'isolation',
    laterality: 'bilateral',
    axialLoading: 'none',
    stabilityDemand: 'low',
    fatigueCost: 1,
    recoveryDemandHours: 24,
    difficulty: 'beginner',
    defaultRepRange: { min: 20, max: 45 },
    defaultRestSeconds: 45,
    isTimeBased: true, // EXPLICITLY TIME BASED
    defaultTimeSeconds: 35,
    progressionMethod: 'density_time',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Maintain a straight rigid line from head to heels on forearms and toes. Squeeze glutes and abdominal wall tight to resist spinal sagging.',
    formTips: [
      'Tuck pelvis into slight posterior tilt.',
      'Push floor away with forearms to protract scapulae.',
      'Breathe rhythmically without dropping hips.'
    ],
    videoUrl: 'https://www.youtube.com/embed/pSHjTRCQxIw'
  },
  {
    name: 'Deadbug (Core Stability)',
    targetMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    movementPattern: 'anti_extension',
    movementSubtype: 'lumbar_anti_extension',
    mechanic: 'isolation',
    laterality: 'unilateral',
    axialLoading: 'none',
    stabilityDemand: 'low',
    fatigueCost: 1,
    recoveryDemandHours: 24,
    difficulty: 'beginner',
    defaultRepRange: { min: 10, max: 14 },
    defaultRestSeconds: 45,
    isTimeBased: false,
    progressionMethod: 'bodyweight_ladder',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Lie on back with arms pointing to ceiling and knees at 90 degrees. Lower opposite arm and leg simultaneously while pressing lower back into floor.',
    formTips: ['Keep lower back glued to floor.', 'Move smoothly and deliberately.'],
    videoUrl: 'https://www.youtube.com/embed/4XLEnwUr1d8'
  },
  {
    name: 'Russian Twists',
    targetMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    movementPattern: 'controlled_rotation',
    movementSubtype: 'rotational_obliques',
    mechanic: 'isolation',
    laterality: 'bilateral',
    axialLoading: 'none',
    stabilityDemand: 'low',
    fatigueCost: 1,
    recoveryDemandHours: 24,
    difficulty: 'beginner',
    defaultRepRange: { min: 12, max: 20 },
    defaultRestSeconds: 45,
    isTimeBased: false,
    progressionMethod: 'double_progression',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Sit in V-shape with torso reclined at 45 degrees holding a dumbbell. Rotate torso from side to side tapping dumbbell beside hips.',
    formTips: ['Rotate ribcage, not just arms.', 'Keep spine tall and neutral.'],
    videoUrl: 'https://www.youtube.com/embed/wkD8rjkodUI'
  },
  {
    name: 'Hanging Leg / Knee Raise',
    targetMuscle: 'core',
    secondaryMuscles: ['forearms'],
    equipment: 'bodyweight',
    movementPattern: 'trunk_flexion',
    movementSubtype: 'hanging_core',
    mechanic: 'isolation',
    laterality: 'bilateral',
    axialLoading: 'none',
    stabilityDemand: 'moderate',
    fatigueCost: 2,
    recoveryDemandHours: 24,
    difficulty: 'intermediate',
    defaultRepRange: { min: 8, max: 12 },
    defaultRestSeconds: 60,
    isTimeBased: false,
    progressionMethod: 'bodyweight_ladder',
    benchRequired: false,
    pullupBarRequired: true,
    pushupHandlesCompatible: false,
    instructions: 'Hang from pull-up bar. Flex abs and raise knees or toes to waist height without swinging momentum.',
    formTips: ['Roll pelvis upward at top of rep.', 'Avoid using body swing.'],
    videoUrl: 'https://www.youtube.com/embed/hdng3Nm1x_E'
  },

  // ==========================================
  // CONDITIONING & WORK CAPACITY
  // ==========================================
  {
    name: 'Dumbbell Thrusters (Conditioning)',
    targetMuscle: 'legs',
    secondaryMuscles: ['shoulders', 'core', 'triceps'],
    equipment: 'dumbbell',
    movementPattern: 'conditioning_circuit',
    movementSubtype: 'full_body_thruster',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'moderate',
    stabilityDemand: 'high',
    fatigueCost: 4,
    recoveryDemandHours: 48,
    difficulty: 'intermediate',
    defaultRepRange: { min: 10, max: 15 },
    defaultRestSeconds: 60,
    isTimeBased: false,
    progressionMethod: 'density_time',
    conditioningClass: 'circuit',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Hold dumbbells at shoulders. Squat to full depth, then explode up using leg drive to push dumbbells overhead in one continuous motion.',
    formTips: [
      'Seamlessly transfer force from hip drive into the overhead press.',
      'Maintain steady breathing rhythm under cardiovascular fatigue.'
    ],
    videoUrl: 'https://www.youtube.com/embed/MeIiIdhvXT4'
  },
  {
    name: 'Push-Up to Renegade Row',
    targetMuscle: 'chest',
    secondaryMuscles: ['back', 'core', 'triceps'],
    equipment: 'dumbbell',
    movementPattern: 'conditioning_circuit',
    movementSubtype: 'push_row_complex',
    mechanic: 'compound',
    laterality: 'unilateral',
    axialLoading: 'none',
    stabilityDemand: 'high',
    fatigueCost: 3,
    recoveryDemandHours: 36,
    difficulty: 'intermediate',
    defaultRepRange: { min: 8, max: 12 },
    defaultRestSeconds: 60,
    isTimeBased: false,
    progressionMethod: 'density_time',
    conditioningClass: 'circuit',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Plank on dumbbells. Perform a full push-up, then row one dumbbell to hip pocket while maintaining square hips. Alternate sides.',
    formTips: ['Widen feet for stability.', 'Keep hips level without twisting.'],
    videoUrl: 'https://www.youtube.com/embed/IODxDxX7oi4'
  },
  {
    name: 'Dumbbell Farmer\'s Walk / Loaded Carry',
    targetMuscle: 'core',
    secondaryMuscles: ['forearms', 'legs', 'shoulders'],
    equipment: 'dumbbell',
    movementPattern: 'conditioning_carry',
    movementSubtype: 'loaded_carry',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'light',
    stabilityDemand: 'moderate',
    fatigueCost: 2,
    recoveryDemandHours: 24,
    difficulty: 'beginner',
    defaultRepRange: { min: 30, max: 60 },
    defaultRestSeconds: 60,
    isTimeBased: true,
    defaultTimeSeconds: 40,
    progressionMethod: 'density_time',
    conditioningClass: 'density',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Hold heavy dumbbells at your sides. Stand tall with retracted shoulders and tight core. Walk in controlled steps for time or distance.',
    formTips: [
      'Do not allow shoulders to roll forward or slump.',
      'Take short, deliberate strides with level hips.'
    ],
    videoUrl: 'https://www.youtube.com/embed/gwLzBJYoWlI'
  },
  {
    name: 'Bodyweight Jump Squat Intervals',
    targetMuscle: 'legs',
    secondaryMuscles: ['core'],
    equipment: 'bodyweight',
    movementPattern: 'conditioning_hiit',
    movementSubtype: 'plyometric_squat',
    mechanic: 'compound',
    laterality: 'bilateral',
    axialLoading: 'none',
    stabilityDemand: 'moderate',
    fatigueCost: 3,
    recoveryDemandHours: 36,
    difficulty: 'intermediate',
    defaultRepRange: { min: 20, max: 40 },
    defaultRestSeconds: 45,
    isTimeBased: true,
    defaultTimeSeconds: 30,
    progressionMethod: 'density_time',
    conditioningClass: 'interval',
    benchRequired: false,
    pullupBarRequired: false,
    pushupHandlesCompatible: false,
    instructions: 'Squat down, then explode upward into a vertical jump. Land softly through balls of feet and absorb into next squat.',
    formTips: ['Land softly like a cat to absorb force.', 'Keep knees tracking out.'],
    videoUrl: 'https://www.youtube.com/embed/MeIiIdhvXT4'
  }
];
